name: Release
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: openjdk:17-slim
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - run: chmod +x ./gradlew

      - run: ./gradlew build publishMod
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          MODRINTH_KEY: ${{ secrets.MODRINTH_KEY }}